Pizzeria/Controllers/ArticoliController.cs
using Pizzeria.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pizzeria.Controllers
{
    [Authorize(Roles ="Admin")]
    public class ArticoliController : Controller
    {
        ModelDbContext context = new ModelDbContext();

        // GET: Articoli
        public ActionResult ListaArticoli()
        {
            List<Articoli>a=context.Articoli.ToList();
            return View(a);
        }

        public ActionResult Add()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(Articoli u,HttpPostedFileBase Foto)
        {


            string source = Path.Combine(Server.MapPath("~/Content/img"), Foto.FileName);

            if (ModelState.IsValid)
            {
            if (Foto != null)
            {
                Foto.SaveAs(source);
                u.Foto=Foto.FileName;
            }

                context.Articoli.Add(u);
                context.SaveChanges();
                return RedirectToAction("ListaArticoli");
            }
            return View();
        }
        public ActionResult DettaglioArticoli(int id)
        {
            Articoli u = context.Articoli.Find(id);
            return View(u);
        }



        public ActionResult ModificaArticolo(int id)
        {
            Articoli u = context.Articoli.Find(id);
            return View(u);
        }

        [HttpPost]
        public ActionResult ModificaArticolo(Articoli u, HttpPostedFileBase Foto)
        {
            string source = Path.Combine(Server.MapPath("~/Content/img"), Foto.FileName);

            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    Foto.SaveAs(source);
                    u.Foto = Foto.FileName;
                }
                context.Entry(u).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("ListaArticoli");

            }
            return View(u);
        }
        public ActionResult Delete(int id)
        {
            Articoli u = context.Articoli.Find(id);
            context.Articoli.Remove(u);
            context.SaveChanges();


            return RedirectToAction("ListaClienti");
        }


    }
}

Pizzeria/Controllers/DettaglioOrdiniController.cs
using Pizzeria.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Pizzeria.Controllers
{
    public class DettaglioOrdiniController : Controller
    {
        ModelDbContext context = new ModelDbContext();

        // GET: DettaglioOrdini
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult AddToCart(int IdArticoli, int quantita, string note)
        {

            if (User.Identity.IsAuthenticated)
            {
                if (Session["id"] == null)
                {
                    HttpCookie cookie = new HttpCookie(".ASPXAUTH");
                    cookie.Expires = DateTime.Now.AddDays(-1);
                    Response.Cookies.Add(cookie);
                    return RedirectToAction("Login", "Utenti");

                }
                else
                {
                    int userId = Convert.ToInt32(Session["id"].ToString());


                    Ordini ordine = context.Ordini.FirstOrDefault(o => o.IdUtenti == userId && o.Stato == "In Attesa");

                    DettagliOrdine dett = new DettagliOrdine();
                    Ordini nuovoOrdine = new Ordini();


                    if (ordine == null)
                    {


                        nuovoOrdine.DataOrdine = DateTime.Now;
                        nuovoOrdine.Stato = "In Attesa";
                        nuovoOrdine.IdUtenti = userId;
                        if (nuovoOrdine.Note == null)
                        {
                            nuovoOrdine.Note = "Nessuna Nota";
                        }
                        else
                        {

                            nuovoOrdine.Note = note;
                        }
                        context.Ordini.Add(nuovoOrdine);



                        dett.IdOrdini = nuovoOrdine.IdOrdini;
                        dett.IdArticoli = IdArticoli;
                        dett.Quantita = quantita;


                        context.DettagliOrdine.Add(dett);
                    }
                    else
                    {


                        DettagliOrdine cart = context.DettagliOrdine.FirstOrDefault(item => item.IdOrdini == ordine.IdOrdini && item.IdArticoli == IdArticoli);


                        if (cart == null)
                        {

                            dett.IdOrdini = ordine.IdOrdini;
                            dett.IdArticoli = IdArticoli;
                            dett.Quantita = quantita;



                            context.DettagliOrdine.Add(dett);
                        }
                        else
                        {

                            cart.Quantita += quantita;
                        }
                    }





                    context.SaveChanges();


                    return RedirectToAction("Pizze", "Home");
                }
            }
            else
            {
                return RedirectToAction("Login", "Utenti");
            }
        }




        public ActionResult ViewCart()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (Session["id"] == null)
                {
                    HttpCookie cookie = new HttpCookie(".ASPXAUTH");
                    cookie.Expires = DateTime.Now.AddDays(-1);
                    Response.Cookies.Add(cookie);
                    return RedirectToAction("Login", "Utenti");

                }
                else
                {
                int userId = Convert.ToInt32(Session["id"].ToString());
                List<Ordini> or = context.Ordini.Where(o => o.IdUtenti == userId).ToList();

                return View(or);
                }
            }
            else
            {
                return RedirectToAction("Login", "Utenti");
            }

        }
        public ActionResult ConfermaOrdine()
        {
            int userId = Convert.ToInt32(Session["id"].ToString());
            Ordini ordine = context.Ordini.FirstOrDefault(o => o.IdUtenti == userId && o.Stato == "In Attesa");

            if (ordine != null)
            {
                ordine.Stato = "In Preparazione";

                List<DettagliOrdine> checkout = context.DettagliOrdine.Where(d => d.IdOrdini == ordine.IdOrdini).ToList();

                context.SaveChanges();
                return RedirectToAction("ViewCart");
            }
            return RedirectToAction("ViewCart");

        }

        public ActionResult RimuoviUno(int id)
        {
            int userId = Convert.ToInt32(Session["id"].ToString());
            DettagliOrdine oneOrdine = context.DettagliOrdine.FirstOrDefault(d => d.IdArticoli == id);
            if (oneOrdine != null)
            {
                context.DettagliOrdine.Remove(oneOrdine);
                context.SaveChanges();
            }

            return RedirectToAction("ViewCart");

        }

        public ActionResult RimuoviAll(int id)
        {
            int userId = Convert.ToInt32(Session["id"].ToString());
            List<Ordini> ordine = context.Ordini.Where(d => d.IdOrdini == id).ToList();
            List<DettagliOrdine>oneOrdine = context.DettagliOrdine.Where(d => d.IdOrdini == id).ToList();
            if (oneOrdine != null)
            {
                context.DettagliOrdine.RemoveRange(oneOrdine);
                context.SaveChanges();
            }
            if (ordine != null)
            {
                context.Ordini.RemoveRange(ordine);
                context.SaveChanges();
                return RedirectToAction("ViewCart");
            }
            return RedirectToAction("ViewCart");

        }
    }
}

Pizzeria/Controllers/UtentiController.cs
using Pizzeria.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Pizzeria.Controllers
{
    public class UtentiController : Controller
    {
        ModelDbContext context = new ModelDbContext();

        // GET: Utenti
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Login(Utenti u)
        {
            var user = context.Utenti.Where(m => m.Username == u.Username).FirstOrDefault();
            if (user.Username == u.Username)
            {
                FormsAuthentication.SetAuthCookie(u.Username, false);
                Session["id"] = user.IdUtenti;
            }
            else
            {
                return View(u);
            }
            return RedirectToAction("Index", "Home");
            
        }


        public ActionResult Registrati()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Registrati(Utenti u)
        {
            if (ModelState.IsValid)
            {

                u.Ruolo = "User";
                var user = context.Utenti.Add(u);
                context.SaveChanges();
                return RedirectToAction("index", "Home");
            }
            return View();
        }

        public ActionResult Logout()
        {
            HttpCookie cookie = new HttpCookie(".ASPXAUTH");
            cookie.Expires = DateTime.Now.AddDays(-1);
            Response.Cookies.Add(cookie);
            return RedirectToAction("Index", "Home");
        }


        [Authorize(Roles = "Admin")]
        public ActionResult ListaClienti()
        {
            List<Utenti> utenti = context.Utenti.Where(m => m.Ruolo != "Admin").ToList();
            return View(utenti);
        }


        public ActionResult DettaglioClienti(int id)
        {
            Utenti u = context.Utenti.Find(id);
            return View(u);
        }


        public ActionResult ModificaCliente(int id)
        {
            Utenti u = context.Utenti.Find(id);
            return View(u);
        }

        [HttpPost]
        public ActionResult ModificaCliente(Utenti u)
        {
            if (ModelState.IsValid)
            {
                context.Entry(u).State = EntityState.Modified;
                context.SaveChanges();
                return RedirectToAction("ListaClienti");

            }
            return View(u);
        }



        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id)
        {
            Utenti u = context.Utenti.Find(id);
            context.Utenti.Remove(u);
            context.SaveChanges();

            return RedirectToAction("ListaClienti");
        }

    }
}

Pizzeria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - In Forno</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="d-flex flex-column justify-content-between" style="height:100vh">
    @if (User.IsInRole("Admin"))
    {


        <header class="p-3 position-sticky top-0 bg-white">
            <nav class="navbar navbar-expand-lg">

                <a href="#" class="d-inline-flex link-body-emphasis text-decoration-none w-25">
                    <img class="navbar-brand w-50" src="https://static.vecteezy.com/ti/vettori-gratis/p3/6814033-vintage-forno-a-legna-mattoni-con-pala-pizza-logo-design-ispirazione-vettoriale.jpg" alt="Alternate Text" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span><i class="bi bi-list"></i></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class=" justify-content-lg-end justify-content-center d-flex w-100">
                        <ul class="navbar nav d-flex flex-column flex-lg-row">
                            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link text-black " })</li>
                            <li> @Html.ActionLink("Clienti", "ListaClienti", "Utenti", new { area = "" }, new { @class = "nav-link me-3 text-black" })</li>

                            <li>@Html.ActionLink("Gestione Pizze", "ListaArticoli", "Articoli", new { area = "" }, new { @class = "nav-link me-3 text-black" }) </li>
                            <li>@Html.ActionLink("Ordini", "ListaOrdini", "Ordini", new { area = "" }, new { @class = "nav-link text-black" })</li>
                            @if (User.Identity.IsAuthenticated)
                            {

                                <li> <a class="nav-link text-dark"> Ciao @User.Identity.Name</a></li>
                                @Html.ActionLink("Logout", "Logout", "Utenti", new { area = "" }, new { @class = "nav-link me-3 btn btn-outline-danger text-dark" })
                            }
                            else
                            {

                                <li>
                                    @Html.ActionLink("Login", "Login", "Utenti", new { area = "" }, new { @class = "nav-link me-3 btn btn-outline-danger text-dark" })
                                </li>

                            }
                        </ul>

                    </div>
                </div>
            </nav>
        </header>

    }
    else
    {

        <header class="p-3 position-sticky top-0 bg-white">
            <nav class="navbar navbar-expand-lg">

                <a href="#" class="d-inline-flex link-body-emphasis text-decoration-none w-25">
                    <img class="navbar-brand w-50" src="https://static.vecteezy.com/ti/vettori-gratis/p3/6814033-vintage-forno-a-legna-mattoni-con-pala-pizza-logo-design-ispirazione-vettoriale.jpg" alt="Alternate Text" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span><i class="bi bi-list"></i></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="justify-content-lg-end justify-content-center d-flex w-100">

                        <ul class="navbar nav d-flex  flex-column flex-lg-row">

                            <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link text-dark" })</li>
                            @if (User.Identity.IsAuthenticated)
                            {

}
else
                {

                                <li>@Html.ActionLink("Registrati", "Registrati", "Utenti", new { area = "" }, new { @class = "nav-link text-dark" })</li>
                }
                                <li>
                                    @Html.ActionLink("Carrello", "ViewCart", "DettaglioOrdini", new { area = "" }, new { @class = "nav-link me-3 text-dark" })
                                </li>
                                @if (User.Identity.IsAuthenticated)
                                {

                                  <li>Ciao</li> @Html.ActionLink(@User.Identity.Name, "DettaglioClienti", "Utenti", new { id = Session["id"] }, new { @class = "nav-link me-3  text-dark" })
                                    @Html.ActionLink("Logout", "Logout", "Utenti", new { area = "" }, new { @class = "nav-link me-3 btn btn-outline-danger text-dark" })
                                }
                                else
                                {

                                    <li>
                                        @Html.ActionLink("Login", "Login", "Utenti", new { area = "" }, new { @class = "nav-link me-3 btn btn-outline-danger text-dark" })
                                    </li>

                                }
                            </ul>
                    </div>
                </div>
            </nav>
        </header>



    }

    <div class="container-fluid body-content flex-grow-1 z">
        @RenderBody()
    </div>

    <footer class="p-3 text-center bg-dark text-bg-dark">
        <p>&copy; @DateTime.Now.Year - In Forno</p>
        <p>P.IVA 123465678</p>
    </footer>


    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)
</body>
</html>